################################################################################
# HC-SR501 Passive Infrared Sensor
################################################################################
# Usage:
#   Add the following code to package section in the device file changing the 
#   I2C Address to the appropriate one.
# -----------------------------------------------------------------------------
# 
# packages:
#  hc-sr501: !include 
#    file: sensors/hc-sr501.yaml
#    vars:
#      pin: GPIO14
#      
################################################################################
sensor:
  - platform: gpio
    pin: ${pin}
    id: ${device_internal_name}_movement
    name: Movement
    device_class: motion