substitutions: #for the name of the fan to input below
  name: bedroomzachbuttonstation #Specific name 
  friendlyname: Bedroom Zach Button Station
  area: Bedroom
  loglevel: DEBUG #NONE or DEBUG
  ip: 10.30.2.9 
  sampling_time: 60s

packages:
  board: !include
    file: packages/board/esp32/nodemcu_simple.yaml
  base: !include 
    file: packages/common/core/base.yaml
  peripheral: !include packages/peripheral/8ButtonESP32.yaml




