substitutions: #for the name of the fan to input below
  name: bedroom #Specific name 
  device_type: atmo_sensor #Device Type
  namefull: "${name}_${device_type}" #Specific name with device type
  nameforesphomefile: "${name}atmosensor"
  loglevel: DEBUG #NONE or DEBUG
  ip: 10.30.2.1

packages:
  base: !include 
    file: packages/common/core/base.yaml
  board: !include   
    file: packages/66/d1mini.yaml
    
  dht22: !include 
    file: packages/sensor/dht22.yaml
    vars:
      pin: D2