---
services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ESPHOME_DASHBOARD_USE_PING=false #optional, set to true if mDNS is not seeing the devices
    volumes:
      - ~/esphome-configs:/config/esphome 
      # nested to be compatable with how the HA ESPhome add on maps
      # this ONLY allows the add on to load the web-browser properly
      # Docker expects the files to be at /config 

    ports:
      - 6052:6052
    restart: unless-stopped