---
services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ESPHOME_DASHBOARD_USE_PING=false #optional, set to true if mDNS is not seeing the devices
    volumes:
      - ~/esphome-configs:/config/esphome 
      # Docker expects the files to be at /config 
      # using /config/esphome as this is required to maintain compatibility with HAs Add On
      # This does prevent the webserver from seeing the files 

    ports:
      - 6052:6052
    restart: unless-stopped