substitutions:
  name: econet-hpwh
  friendly_name: Water Heater
  loglevel: DEBUG #NONE or DEBUG
 # ip: 10.30.2.18 Doesnt want to take a static IP
  sampling_time: 60s

packages:
  esphome-econet.esphome-econet: github://esphome-econet/esphome-econet/build-yaml/econet-hpwh-esp32s3.yaml@main
  base: !include 
    file: packages/common/core/base.yaml
