substitutions: #for the name of the fan to input below
  name: greenhouse #Specific name 
  namefull: "${name}" #Specific name with device type
  nameforesphomefile: "${name}"
  loglevel: DEBUG #NONE or DEBUG
  ip: 10.30.2.4
  
packages:
  base: !include 
    file: packages/common/core/base.yaml
  board: !include   
    file: packages/board/esp8266/d1minisimple.yaml
    
  dht22: !include
    file: packages/sensor/dht22.yaml
    vars:
      pin: D2