substitutions: #for the name of the fan to input below
  name: kitchenled01 #Specific name 
  namefull: "${name}" #Specific name with device type
  nameforesphomefile: "${name}"
  loglevel: DEBUG #NONE or DEBUG
  ip: 10.30.2.11

packages:
  base: !include 
    file: packages/common/core/base.yaml
  board: !include   
    file: packages/board/esp8266/d1minisimple.yaml
  
  dimmer: !include 
    file: packages/lighting/singledimmer.yaml
    vars:
      pin: D8