################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include common/esp8266/d1_mini.yaml
# ------------------------------------------------------------------------------
# This version includes all of the onboard functionality
################################################################################
esp8266:
  board: d1_mini
  framework: 
    #type: arduino
    version: latest

# Status led
status_led:
  pin:
    number: GPIO2
    inverted: true

# I2C settings
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: ${name}_i2c

# UART
uart:
  id: ${name}_uart_presence
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# SPI
spi:
  mosi_pin: GPIO12
  miso_pin: GPIO13
  clk_pin: GPIO14
  #cs_pin: GPIO15

sensor:
  - platform: adc
    pin: VCC
    name: "Chip Voltage"
    entity_category: diagnostic
    disabled_by_default: true