# For the config file:
# packages:
#   bh1750: !include 
#     file: packages/bh1750.yaml
#     vars:
#       address: 0x23 #Changeme accordingly

sensor:
  - platform: bh1750
    name: "${namefull}_lux"
    address: ${address}
    update_interval: 60s #Default

#Configuration variables:
#name (Required, string): The name for the sensor.
##address (Optional, int): Manually specify the I²C address of the sensor. Defaults to 0x23 (address if address pin is pulled low). If the address pin is pulled high, the address is 0x5C.
#update_interval (Optional, Time): The interval to check the sensor. Defaults to 60s.
#id (Optional, ID): Manually specify the ID used for code generation.
#All other options from Sensor.

