################################################################################
# DTH11/22 Temperature and Humidity Sensor
################################################################################
# Usage:
#   Add the following code to package section in the device file changing the 
#   pin to the coorect pin
# packages:
#   dht22: !include 
#     file: packages/dht22.yaml
#     vars:
#       pin: D2
################################################################################

sensor:
  - platform: dht # Temp and Humidity
    model: AM2302
    pin: ${pin}
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: ${sampling_time}
