esphome:
  name: boiler-thermostat
  friendly_name: boiler-thermostat

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "e8es/8LS4sYJMpX7W43Tj06Zg0343O9KQcVsnQb2cCI="

ota:
  password: "aa2bee1f6e0bda8c6e693194a4d19020"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boiler-Thermostat"
    password: "0156mPDLcBX8"

captive_portal:
    