substitutions: #for the name of the fan to input below
  name: bedroom #Specific name 
  device_type: atmo_sensor #Device Type
  namefull: "${name}_${device_type}" #Specific name with device type
  nameforesphomefile: "${name}atmosensor"
  loglevel: DEBUG #NONE or DEBUG
  
  platform: ESP8266
  board: d1_mini
  ip: 10.30.2.X

packages:
  common: !include packages/base.yaml


