substitutions: #for the name of the fan to input below
  name: kitchenled02 #Specific name 
  namefull: "${name}" #Specific name with device type
  nameforesphomefile: "${name}"
  loglevel: DEBUG #NONE or DEBUG
  
  platform: ESP8266
  board: d1_mini
  ip: 10.30.2.12

packages:
  common: !include packages/base.yaml
  dimmer: !include packages/singledimmer.yaml