uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor: #What to do with the onboard button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${namefull}_button"
    on_press:
      - switch.toggle: relay

time:
  - platform: homeassistant
    id: homeassistant_time

sensor: 
  - platform: cse7766 #Sensors for Power monitoring
    current:
      name: "${namefull}_current"
      accuracy_decimals: 1
      
    voltage:
      name: "${namefull}_voltage"
      accuracy_decimals: 1
    
    power:
      name: "${namefull}_wattage"
      accuracy_decimals: 1
      id: wattage
      
  - platform: total_daily_energy
    name: "${namefull}_total_daily_energy"
    power_id: "wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh    

switch:
  - platform: gpio #Smart Switch Itself
    name: "${namefull}_relay"
    pin: GPIO12
    id: relay

status_led:
  pin: 
    number: GPIO13
    inverted: True