################################################################################
# Board Specific Configurations - Untested
################################################################################
esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino
    version: latest
    platform_version: 5.3.0

# Captive Portal
captive_portal:

# Status led
status_led:
  id: ${device_internal_name}_status_led
  pin:
    number: GPIO2
    inverted: false

# I2C settings
i2c:
  id: ${device_internal_name}_i2c_bus0
  sda: GPIO39
  scl: GPIO40
  scan: true

# UART
uart:
  id: ${device_internal_name}_uart_bus0
  tx_pin: GPIO37
  rx_pin: GPIO38
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# SPI
spi:
  id: ${device_internal_name}_spi_bus0
  clk_pin: GPIO34
  mosi_pin: GPIO35
  miso_pin: GPIO36
  interface: hardware

# Sensors
sensor:
  # Internal Temperature Sensor
  - platform: internal_temperature
    id: ${device_internal_name}_internal_temperature
    name: "Internal Temperature"
    update_interval: ${device_sampling_time}
    disabled_by_default: true
    